packages:
  - backend/*
  - packages/*

catalog:
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@nestjs/common': 11.0.1
  '@nestjs/core': 11.0.1
  '@nestjs/jwt': 11.0.2
  '@nestjs/platform-express': 11.0.1
  '@prisma/adapter-pg': 7.2.0
  '@prisma/client': 7.2.0
  '@rollup/plugin-typescript': 12.3.0
  '@types/node': 25.0.3
  '@typescript-eslint/parser': 8.53.0
  '@typescript-eslint/utils': 8.53.0
  class-transformer: 0.5.1
  class-validator: 0.14.3
  cookie-parser: 1.4.7
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  eslint-plugin-prettier: 5.5.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react: 7.37.5
  eslint: 9.39.2
  jiti: 2.6.1
  kafkajs: 2.2.4
  prettier: 3.8.0
  prisma: 7.2.0
  reflect-metadata: 0.2.2
  rollup: 4.55.1
  rxjs: 7.8.1
  ts-invariant: 0.10.3
  tslib: 2.8.1
  typescript-eslint: 8.52.0
  typescript: 5.7.3
  vite-tsconfig-paths: 6.0.3
  vite: 7.3.1
  globals: 17.0.0

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'

catalogMode: prefer
injectWorkspacePackages: true
