packages:
  - 'backend/*'
  - 'packages/*'

catalog:
  '@nestjs/common': 11.0.1
  '@nestjs/core': 11.0.1
  '@nestjs/jwt': 11.0.2
  '@nestjs/platform-express': 11.0.1
  '@prisma/adapter-pg': 7.2.0
  '@prisma/client': 7.2.0
  class-transformer: 0.5.1
  class-validator: 0.14.3
  cookie-parser: 1.4.7
  kafkajs: 2.2.4
  prisma: 7.2.0
  reflect-metadata: 0.2.2
  rxjs: 7.8.1
  ts-invariant: 0.10.3
  typescript: 5.7.3
  vite-tsconfig-paths: 6.0.3
  vite: 7.3.1

injectWorkspacePackages: true
